### ISSUE TITLE
256 color support

### ISSUE THREAD

**Issue by bzar** [nemomobile/fingerterm#48]
According to `tput colors`, fingerterm currently only supports 8 colors. While this is certainly enough for most tasks, many console oriented applications would benefit from having access to a wider palette. Any possibility of adding support for 256 colors?

**Comment by bzar** [comment]
TERM=xterm-256color in environment fixed this, should've tried first.

**Comment by Kabouik** [comment]
In SFOS, if I use anything else than `export TERM=xterm-color` in my `~/.bash_profile`, Fingerterm refreshing will be totally garbled in many CLI tools. The most obvious are `nano` and `cmus` from what I tested so far, so I'm stuck with 8 colours and the fix is not 100% working (it improves the refreshing issue a lot though).
